# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

payoneer: &payoneer
  partner_id: '***REMOVED***'
  partner_username: '***REMOVED***'
  partner_api_password: '***REMOVED***'

development:
  secret_key_base: 652b99c18953f4f1192789cda640decfc144a9453aa8c5a289838ba5137d839db7758aff9f43623a73c188de611ea6f758109252d45c5f5a5fda7d9117ea1b19
  <<: *payoneer

test:
  secret_key_base: 267ae90f3cf891235516284811966927fd4875ea6a62ee769e0b5130d879a392414d74a46bd35bb4b77a83d5aefbfa933680a5bec434157108d745ca5d6b3359
  <<: *payoneer

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
